#!/usr/bin/env python3
import os
from PIL import Image, ImageDraw, ImageFont
from bidi.algorithm import get_display

SRC   = r"C:\VirtualDrive\SLH_ECOSYSTEM\esp-firmware\src"
FONTS = r"C:\VirtualDrive\SLH_ECOSYSTEM\esp-firmware\fonts"
TTF   = os.path.join(FONTS, "DavidLibre-Regular.ttf")

W, H = 320, 200
WHITE=(255,255,255); GOLD=(254,220,140); RED=(249,100,100)
GREEN=(100,240,120); BLUE=(120,200,255); DIM=(150,150,150); BG=(0,0,0)

lessons = [
  ("\u05e1\u05b0\u05e4\u05bc\u05b6\u05e8\u05b6\u05d3 - \u05de\u05d4 \u05d6\u05d4?", [
    ('dot',  "\u05d1\u05db\u05dc \u05de\u05d8\u05d1\u05e2 \u05d9\u05e9 \u05e9\u05e0\u05d9 \u05de\u05d7\u05d9\u05e8\u05d9\u05dd", WHITE),
    ('dot',  "\u05e7\u05e0\u05d9\u05d9\u05d4 \u05d5\u05de\u05db\u05d9\u05e8\u05d4", DIM),
    ('dot',  "\u05d4\u05d4\u05e4\u05e8\u05e9 = \u05e1\u05b0\u05e4\u05bc\u05b6\u05e8\u05b6\u05d3", GOLD),
    ('none', "\u05d3\u05d5\u05d2\u05de\u05d4: BTC \u05d1-70,000$", BLUE),
    ('none', "\u05e7\u05d5\u05e0\u05d9\u05dd \u05d1-70,010 \u05de\u05d5\u05db\u05e8\u05d9\u05dd \u05d1-69,990", DIM),
    ('none', "\u05d4\u05e4\u05e1\u05d3 \u05de\u05d9\u05d9\u05d3\u05d9 20$ \u05dc\u05db\u05dc \u05e2\u05e1\u05e7\u05d4", RED),
  ]),
  ("\u05d2\u05d5\u05d3\u05dc \u05d4\u05e4\u05d5\u05d6\u05d9\u05e6\u05d9\u05d4", [
    ('dot',  "\u05d7\u05d5\u05e7: \u05e1\u05d9\u05db\u05d5\u05df \u05de\u05e7\u05e1\u05d9\u05de\u05dc\u05d9 1%", WHITE),
    ('dot',  "\u05de\u05d4\u05d7\u05e9\u05d1\u05d5\u05df \u05dc\u05e2\u05e1\u05e7\u05d4", DIM),
    ('none', "\u05d7\u05e9\u05d1\u05d5\u05df 10,000$ = \u05e1\u05d9\u05db\u05d5\u05df 100$", BLUE),
    ('dot',  "\u05e1\u05d8\u05d5\u05e4 1% - \u05e4\u05d5\u05d6\u05d9\u05e6\u05d9\u05d4 10,000$", WHITE),
    ('dot',  "\u05e1\u05d8\u05d5\u05e4 0.5% - \u05e4\u05d5\u05d6\u05d9\u05e6\u05d9\u05d4 20,000$", WHITE),
    ('none', "\u05d4\u05e1\u05d8\u05d5\u05e4 \u05e7\u05d5\u05d1\u05e2 \u05d0\u05ea \u05d4\u05d2\u05d5\u05d3\u05dc", GOLD),
  ]),
  ("\u05e1\u05d9\u05db\u05d5\u05df \u05de\u05d5\u05dc \u05e1\u05d9\u05db\u05d5\u05d9", [
    ('dot',  "\u05db\u05dc \u05e2\u05e1\u05e7\u05d4 = \u05e1\u05d8\u05d5\u05e4 + \u05d9\u05e2\u05d3", WHITE),
    ('dot',  "\u05d9\u05d7\u05e1 \u05d1\u05e8\u05d9\u05d0: 1 \u05dc-2 \u05dc\u05e4\u05d7\u05d5\u05ea", GOLD),
    ('none', "\u05e1\u05d9\u05db\u05d5\u05df 100$, \u05d9\u05e2\u05d3 200$", BLUE),
    ('dot',  "4 \u05de-10 \u05de\u05e0\u05e6\u05d7\u05d5\u05ea = +200$", GREEN),
    ('dot',  "6 \u05de-10 \u05de\u05e0\u05e6\u05d7\u05d5\u05ea = +800$", GREEN),
    ('none', "\u05d2\u05dd 40% \u05d4\u05e6\u05dc\u05d7\u05d4 = \u05e8\u05d5\u05d5\u05d7", GOLD),
  ]),
  ("\u05e6'\u05e7\u05dc\u05d9\u05e1\u05d8 \u05db\u05e0\u05d9\u05e1\u05d4", [
    ('dot',  "1. \u05ea\u05e0\u05d5\u05e2\u05d4 \u05d9\u05d5\u05de\u05d9\u05ea \u05de\u05e2\u05dc 3%", WHITE),
    ('dot',  "2. \u05e2\u05de\u05dc\u05d5\u05ea \u05e4\u05d7\u05d5\u05ea \u05de-30% \u05de\u05d4\u05ea\u05e0\u05d5\u05e2\u05d4", WHITE),
    ('dot',  "3. \u05de\u05d7\u05d9\u05e8 \u05d1\u05e7\u05e6\u05d4 \u05d4\u05d8\u05d5\u05d5\u05d7", WHITE),
    ('dot',  "4. \u05e1\u05d8\u05d5\u05e4 \u05d1\u05e8\u05d5\u05e8 \u05dc\u05e4\u05e0\u05d9 \u05d4\u05db\u05e0\u05d9\u05e1\u05d4", WHITE),
    ('dot',  "5. \u05d9\u05e2\u05d3 \u05e4\u05d9 2 \u05de\u05d4\u05e1\u05d9\u05db\u05d5\u05df", WHITE),
    ('none', "\u05d0\u05d9\u05df \u05e1\u05d8\u05d5\u05e4 = \u05d0\u05d9\u05df \u05db\u05e0\u05d9\u05e1\u05d4", RED),
  ]),
]

title_font = ImageFont.truetype(TTF, 26)
line_font  = ImageFont.truetype(TTF, 17)
pages = []

for idx, (title, lines) in enumerate(lessons):
    img = Image.new("RGB", (W, H), BG)
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, W, 34], fill=(20, 20, 30))
    d.line([0, 34, W, 34], fill=GOLD, width=2)
    vt = get_display(title)
    bbox = d.textbbox((0, 0), vt, font=title_font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    d.text(((W - tw) // 2 - bbox[0], (34 - th) // 2 - bbox[1]), vt, font=title_font, fill=GOLD)
    y = 46
    for btype, text, color in lines:
        v = get_display(text)
        bbox = d.textbbox((0, 0), v, font=line_font)
        tw = bbox[2] - bbox[0]
        if btype == 'dot':
            d.ellipse([W - 12, y + 7, W - 6, y + 13], fill=color)
            text_right = W - 20
        else:
            text_right = W - 12
        d.text((text_right - tw - bbox[0], y), v, font=line_font, fill=color)
        y += 24
    png = os.path.join(FONTS, "lesson_%d.png" % idx)
    img.save(png)
    px = img.load()
    rgb = bytearray(W * H)
    for yy in range(H):
        for xx in range(W):
            r, g, b = px[xx, yy]
            rgb[yy * W + xx] = ((r >> 5) << 5) | ((g >> 5) << 2) | (b >> 6)
    pages.append(rgb)
    print("[OK] page %d" % idx)

out = os.path.join(SRC, "lesson_bitmaps.h")
with open(out, "w", encoding="ascii") as f:
    f.write("// AUTO-GENERATED by render_lessons.py\n#pragma once\n#include <Arduino.h>\n\n")
    f.write("const uint16_t LESSON_W   = %d;\n" % W)
    f.write("const uint16_t LESSON_H   = %d;\n" % H)
    f.write("const uint16_t LESSON_TOP = 0;\n\n")
    for i, data in enumerate(pages):
        f.write("const uint8_t LESSON_PAGE_%d[%d] PROGMEM = {\n" % (i, len(data)))
        for j in range(0, len(data), 16):
            f.write("  " + ",".join("0x%02X" % b for b in data[j:j+16]) + ",\n")
        f.write("};\n\n")
    f.write("const uint8_t* const LESSON_PAGES[4] = { LESSON_PAGE_0, LESSON_PAGE_1, LESSON_PAGE_2, LESSON_PAGE_3 };\n")
print("[OK] header written")

lesson_h = '''#pragma once
#include "lesson_bitmaps.h"

static int           g_lessonPage     = 0;
static unsigned long g_lessonLastFlip = 0;
static const int     LESSON_COUNT     = 4;
static const unsigned long LESSON_FLIP_MS = 12000UL;

static inline uint16_t rgb332_to_565(uint8_t px) {
    uint16_t r = (px >> 5) & 0x07;
    uint16_t g = (px >> 2) & 0x07;
    uint16_t b =  px       & 0x03;
    r = (r << 2) | (r >> 1);
    g = (g << 3) |  g;
    b = (b << 3) | (b << 1) | (b >> 1);
    return (r << 11) | (g << 5) | b;
}

void drawLessonPage(int n) {
    if (n < 0 || n >= LESSON_COUNT) n = 0;
    const uint8_t* src = LESSON_PAGES[n];
    static uint16_t rowBuf[320];
    for (int y = 0; y < (int)LESSON_H; y++) {
        for (int x = 0; x < (int)LESSON_W; x++) {
            rowBuf[x] = rgb332_to_565(pgm_read_byte(&src[y * LESSON_W + x]));
        }
        tft.pushImage(0, LESSON_TOP + y, LESSON_W, 1, rowBuf);
    }
    tft.fillRect(0, 200, 320, 40, C_BG);
    tft.setTextDatum(MC_DATUM);
    tft.setTextColor(C_DIM, C_BG);
    tft.drawString("touch = next screen", 160, 220, 2);
    tft.setTextDatum(TL_DATUM);
}

void drawLessonScreen() {
    drawLessonPage(g_lessonPage);
    g_lessonLastFlip = millis();
}

void updateLessonScreen() {
    if (millis() - g_lessonLastFlip >= LESSON_FLIP_MS) {
        g_lessonPage = (g_lessonPage + 1) % LESSON_COUNT;
        drawLessonPage(g_lessonPage);
        g_lessonLastFlip = millis();
    }
}
'''
with open(os.path.join(SRC, "lesson.h"), "w", encoding="utf-8") as f:
    f.write(lesson_h)
print("[OK] lesson.h rewritten")